apiVersion: v1
kind: ConfigMap
data:
  PGDATA: /var/lib/postgresql/data/db-files/
  POSTGRES_DB: todo
  POSTGRES_PASSWORD: Heslo123
  POSTGRES_USER: miro
metadata:
  labels:
    app: database
  name: database
  namespace: todo
