apiVersion: v1
kind: Service
metadata:
  labels:
    app: ui
  name: ui
  namespace: todo
spec:
  ports:
  - name: http
    port: 9080
  selector:
    app: ui
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: todo
  name: todo
  namespace: todo
spec:
  ports:
  - name: http
    port: 9080
  selector:
    app: todo
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: database
  name: database
  namespace: todo
spec:
  ports:
  - name: cloudsql
    port: 5432
  selector:
    app: database
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  name: todo
  namespace: todo
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: todo
          servicePort: 8080
        path: /todo(/|$)(.*)
      - backend:
          serviceName: ui
          servicePort: 8080
        path: /ui(/|$)(.*)
