apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: todo-list
spec:
  profile: demo
  components:
    ingressGateways:
    - name: todo-ingressgateway
      enabled: true
      k8s:
        service:
          ports:
          - name: http
            port: 8080
            targetPort: 8080
