apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
commonLabels:
  sidecar.istio.io/inject: "true"
images:
- name: localhost:5000/ui
  newName: localhost:5000/ui
  newTag: v675
