apiVersion: v1
kind: ConfigMap
metadata:
  name: database
  labels:
    app: database
data:
  POSTGRES_USER: miro
  POSTGRES_PASSWORD: Heslo123
  POSTGRES_DB: todo
  PGDATA: /var/lib/postgresql/data/db-files/