apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  labels:
    sidecar.istio.io/inject: "true"
spec:
  selector:
    matchLabels:
      app: database
  replicas: 1
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: database
        image: postgres
        ports:
        - containerPort: 5432
        envFrom:
        - configMapRef:
            name: database
#        volumeMounts:
#        - name: postgresql-persistent-storage
#          mountPath: /var/lib/postgresql/data
#      volumes:
#      - name: postgresql-persistent-storage
#        persistentVolumeClaim:
#          claimName: postgresql-pv-claim

