apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: todo

images:
- name: gcr.io/miroc-sandbox/todo
  newName: gcr.io/miroc-sandbox/todo
  newTag: latest
- name: gcr.io/miroc-sandbox/ui
  newName: gcr.io/miroc-sandbox/ui
  newTag: latest

resources:
- ../bases
- ./bases
