apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: gcr.io/miroc-sandbox/todo
  newName: gcr.io/miroc-sandbox/todo
  newTag: v0.0.3
- name: gcr.io/miroc-sandbox/ui
  newName: gcr.io/miroc-sandbox/ui
  newTag: v0.0.3

resources:
- ../bases
- ./bases
