apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: todo
spec:
  selector:
    istio: todo-ingressgateway
  servers:
  - port:
      number: 8080
      name: http
      protocol: HTTP
    hosts:
    - "*"
