apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: todo-list
resources:
- deployment.yaml
- service.yaml
- virtual-service.yaml
images:
- name: localhost:5000/todo
  newName: localhost:5000/todo
  newTag: v1
commonLabels:
  sidecar.istio.io/inject: "true"
