apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: todo

resources:
- namespace.yaml

- ui/deployment.yaml
- ui/service.yaml
- ui/serviceaccount.yaml

- todo/deployment.yaml
- todo/service.yaml
- todo/serviceaccount.yaml

- postgres/deployment.yaml
- postgres/service.yaml
- postgres/config-map.yaml
