apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo
  labels:
    sidecar.istio.io/inject: "true"
spec:
  selector:
    matchLabels:
      app: todo
  replicas: 1
  template:
    metadata:
      labels:
        app: todo
    spec:
      serviceAccountName: todo-todo
      containers:
      - name: todo
        image: gcr.io/miroc-sandbox/todo
        ports:
        - containerPort: 9080
        envFrom:
        - configMapRef:
            name: database
