apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  labels:
    sidecar.istio.io/inject: "true"
spec:
  selector:
    matchLabels:
      app: ui
  replicas: 1
  template:
    metadata:
      labels:
        app: ui
    spec:
      serviceAccountName: todo-ui
      containers:
      - name: ui
        image: gcr.io/miroc-sandbox/ui
        ports:
        - containerPort: 9080
        envFrom:
        - configMapRef:
            name: database
        livenessProbe:
          httpGet:
            path: /healthz
            port: 9080
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /healthz
            port: 9080
          initialDelaySeconds: 3
          periodSeconds: 3
