apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  labels:
    sidecar.istio.io/inject: "true"
spec:
  selector:
    matchLabels:
      app: ui
  replicas: 1
  template:
    metadata:
      labels:
        app: ui
    spec:
      serviceAccountName: todo-ui
      containers:
      - name: ui
        image: gcr.io/miroc-sandbox/ui
        ports:
        - containerPort: 9080
